# pylint: disable=too-few-public-methods
"""ViewModel handling hardware device connection logic off the UI thread.

Encapsulates the background task to fetch Ledger xpubs/fingerprint and exposes
signals for the view/dialog to react to start, success and error.
"""
from __future__ import annotations

from hwilib.common import Chain
from hwilib.devices.ledger import LedgerClient
from PySide6.QtCore import QCoreApplication
from PySide6.QtCore import QObject
from PySide6.QtCore import Signal

from src.model.enums.enums_model import NetworkEnumModel
from src.utils.constant import ACCOUNT_XPUB_COLORED
from src.utils.constant import ACCOUNT_XPUB_VANILLA
from src.utils.constant import IRIS_WALLET_TRANSLATIONS_CONTEXT
from src.utils.constant import MASTER_FINGERPRINT
from src.utils.local_store import local_store
from src.utils.worker import ThreadManager
from src.views.components.toast import ToastManager


class HWDeviceSelectionViewModel(QObject, ThreadManager):
    """Runs hardware device connect in background and emits results."""

    connect_succeeded = Signal()
    connect_failed = Signal(object)

    def __init__(self) -> None:
        super().__init__()

    def connect_to_device(self, device_path: str, network: NetworkEnumModel, is_multisig: bool = False) -> None:
        """Start background job to fetch xpubs/fingerprint for the given device."""
        self.run_in_thread(
            self._fetch_ledger_xpubs,
            {
                'args': [device_path, network, is_multisig],
                'callback': self.on_ledger_success,
                'error_callback': self.on_ledger_error,
            },
        )

    def _fetch_ledger_xpubs(self, device_path: str, network: NetworkEnumModel, is_multisig: bool = False):
        """Worker method executed off the UI thread.

        Returns: tuple (vanilla_xpub, colored_xpub, fingerprint)
        """
        try:
            if network == NetworkEnumModel.MAINNET:
                chain = Chain.MAIN
                # BIP-48: m/48'/0'/0'/2' for Mainnet Native Segwit Multisig
                multisig_path = "m/48h/0h/0h/2h"
            elif network == NetworkEnumModel.TESTNET:
                chain = Chain.TEST
                # BIP-48: m/48'/1'/0'/2' for Testnet Native Segwit Multisig
                multisig_path = "m/48h/1h/0h/2h"
            else:
                chain = Chain.REGTEST
                # BIP-48: m/48'/1'/0'/2' for Regtest Native Segwit Multisig (using testnet coin type)
                multisig_path = "m/48h/1h/0h/2h"
            
            client = LedgerClient(device_path, None, True, chain)
            
            if is_multisig:
                # For multisig, we use the BIP-48 path for both vanilla and colored xpubs
                # Note: Currently using the same path for colored as vanilla for multisig setup 
                # or we might need a specific derivation if RGB implies something else.
                # Based on the requirement, we just need to use the hardware wallet for multisig setup.
                # The single-sig flow used 'm/86h/1h/0h' and 'm/86h/827167h/0h'.
                # For multisig, we will use the standard BIP-48 path.
                
                vanilla = client.get_pubkey_at_path(multisig_path).to_string()
                # For colored, typically we might use a different index or path, 
                # but valid RGB multisig specs might require specific handling.
                # Assuming simple reuse or a specific offset if defined.
                # However, looking at the single sig pattern:
                # Vanilla: m/86'/1'/0'
                # Colored: m/86'/827167'/0'
                # Let's try to follow a similar pattern if possible, OR just use the same xpub if the wallet logic handles it.
                # But typically they should be different.
                # The existing code for Hot Multisig (software) reuses the same keys generated by `rgb_lib.generate_keys`.
                # Let's check `rgb_lib` behavior or just use a distinct path for colored if possible.
                # To be safe and minimal: use a modified path for colored if strictly needed, 
                # but if the user just wants "online hardware part", we should align with how `rgb_lib` expects it.
                # `rgb_lib` (rust) likely expects xpubs. 
                # Let's assume for now we use a different account index or similar for colored if we want separation,
                # BUT `rgb_lib` might manage RGB assets on the same UTXOs/keys in some modes.
                # However, strictly following the previous pattern:
                # Let's use m/48'/<coin_type>'/827167'/2' for colored if we want to mimic the single sig separation?
                # WAITING: The robust way is to ask the client what paths to use, but standard RGB wallets often share.
                # Let's stick to the vanilla path for vanilla and maybe a slight variation for colored?
                # Actually, `InitRequestModel` in `CommonOperationRepository.unlock` uses `keys.account_xpub_colored`.
                # If we look at `MultisigSetupPage.py` review screen, it shows `account_xpub_colored`.
                # Let's define:
                multisig_colored_path = multisig_path.replace("0h/2h", "827167h/2h") 
                 
                vanilla = client.get_pubkey_at_path(multisig_path).to_string()
                colored = client.get_pubkey_at_path(multisig_colored_path).to_string()
            else:
                vanilla = client.get_pubkey_at_path('m/86h/1h/0h').to_string()
                colored = client.get_pubkey_at_path('m/86h/827167h/0h').to_string()
            
            fingerprint = client.get_master_fingerprint().hex()
            
            # Fetch Master XPUB (required for biscuit auth / bridge token)
            # Path 'm' corresponds to the root extended public key of the device's seed.
            master_xpub = client.get_pubkey_at_path('m').to_string()
            
            return vanilla, colored, fingerprint, master_xpub
        except Exception as e:
            self.connect_failed.emit(str(e))
            return None, None, None, None

    def on_ledger_success(self, result):
        """
        Handle successful retrieval of xpubs and fingerprint from Ledger.
        """
        if result:
            vanilla, colored, fingerprint, master_xpub = result
            local_store.set_value(ACCOUNT_XPUB_VANILLA, vanilla)
            local_store.set_value(ACCOUNT_XPUB_COLORED, colored)
            local_store.set_value(MASTER_FINGERPRINT, fingerprint)
            if master_xpub:
                # Add import for MASTER_XPUB if needed, though it seems already imported or available
                # Checking imports... imported at top.
                from src.utils.constant import MASTER_XPUB
                local_store.set_value(MASTER_XPUB, master_xpub)
                
            self.connect_succeeded.emit()

    def on_ledger_error(self, error):
        """
        Handle error during Ledger xpub/fingerprint retrieval.
        """
        ToastManager.error(
            QCoreApplication.translate(
                IRIS_WALLET_TRANSLATIONS_CONTEXT, 'failed_to_fetch_xpubs',
            ).format(error),
        )
        self.connect_failed.emit(error)
