[pytest]
testpaths = e2e_tests/tests/spec
addopts = -s --alluredir=allure-results
markers =
    skip_for_offline_wallet: mark test to skip when running in offline wallet mode
    skip_for_hardware_wallet: mark test to skip when running against a hardware wallet
    skip_for_online: mark test to skip when running in online wallet mode
    skip_for_create_wallet_variants: mark test to skip when running create wallet variant
    skip_for_load_wallet_variants: mark test to skip when running load wallet variant
