"""This module contains the list of error names and their custom message"""
from __future__ import annotations

from src.utils.error_message import ERROR_SOMETHING_WENT_WRONG


ERROR_MAPPING = {
    'InvalidAddress': 'invalid_address',
    'InvalidAmountZero': 'invalid_amount',
    'InvalidAssetId': 'invalid_asset_id',
    'InvalidAttachments': 'invalid_attachment',
    'InvalidDetails': 'invalid_details',
    'InvalidElectrum': 'invalid_electrum',
    'InvalidEstimationBlocks': 'invalid_estimation_blocks',
    'InvalidFeeRate': 'invalid_fee_rate',
    'InvalidFilePath': 'invalid_file_path',
    'InvalidMnemonic': 'invalid_mnemonic',
    'InvalidName': 'invalid_name',
    'InvalidPrecision': 'invalid_precision',
    'InvalidProxyProtocol': 'invalid_proxy_protocol',
    'InvalidPsbt': 'invalid_psbt',
    'InvalidPubkey': 'invalid_pubkey',
    'InvalidRecipientData': 'invalid_recipient_data',
    'InvalidRecipientId': 'invalid_recipient_id',
    'InvalidRecipientNetwork': 'invalid_recipient_network',
    'InvalidTicker': 'invalid_ticker',
    'InvalidTransportEndpoint': 'invalid_transport_endpoint',
    'InvalidTransportEndpoints': 'invalid_transport_endpoints',
    'InvalidTxid': 'invalid_txid',
    'InvalidVanillaKeychain': 'invalid_vanilla_keychain',
    'InvalidIndexer': 'invalid_indexer',
    'MaxFeeExceeded': 'max_fee_exceeded',
    'MinFeeNotMet': 'min_fee_not_met',
    'NoConsignment': 'no_consignment',
    'NoIssuanceAmounts': 'no_issuance_amounts',
    'NoValidTransportEndpoint': 'no_valid_transpoint_endpoint',
    'Offline': 'offline',
    'OnlineNeeded': 'online_needed',
    'Proxy': 'proxy_error',
    'RecipientIdAlreadyUsed': 'recipient_id_already_used',
    'RecipientIdDuplicated': 'recipient_id_duplicated',
    'SyncNeeded': 'sync_needed',
    'TooHighIssuanceAmounts': 'too_high_issuance_amounts',
    'UnknownRgbInterface': 'unknown_rgb_interface',
    'UnknownRgbSchema': 'unknown_rgb_schema',
    'UnsupportedBackupVersion': 'unsupported_backup_version',
    'UnsupportedLayer1': 'unsupported_layer_1',
    'UnsupportedTransportType': 'unsupported_transport_type',
    'Network': 'network_error',
    'JsonExtractorRejection': ERROR_SOMETHING_WENT_WRONG,
    'WalletDirAlreadyExists': 'wallet_dir_already_exists',
    'WatchOnly': 'watch_only',
    'WrongPassword': 'wrong_password',
    'InvalidInvoice': 'invalid_invoice_error',
    'OutputBelowDustLimit': 'output_below_dust_limit',
    'AllocationsAlreadyAvailable': 'allocations_already_available',
    'AssetIfaceMismatch': 'asset_iface_mismatch',
    'AssetNotFound': 'asset_not_found',
    'BatchTransferNotFound': 'batch_transfer_not_found',
    'BitcoinNetworkMismatch': 'bitcoin_network_mismatch',
    'CannotChangeOnline': 'cannot_change_online',
    'CannotDeleteBatchTransfer': 'cannot_delete_batch_transfer',
    'CannotEstimateFees': 'cannot_estimate_fees',
    'CannotFailBatchTransfer': 'cannot_fail_batch_transfers',
    'EmptyFile': 'empty_file',
    'FailedBdkSync': 'failed_bdk_sync',
    'FailedBroadcast': 'failed_broadcast',
    'FailedIssuance': 'failed_issuing_asset',
    'FileAlreadyExists': 'file_already_exists',
    'Inconsistency': 'inconsistency_error',
    'Indexer': 'indexer_error',
    'InexistentDataDir': 'inexistent_data_dir',
    'InsufficientAllocationSlots': 'insufficient_allocation_slots',
    'InsufficientSpendableAssets': 'insufficient_spendable_assets',
    'Io': 'io_error',
    'InsufficientTotalAssets': 'insufficient_total_assets',
    'Internal': 'internal_error',
    'InvalidBitcoinKeys': 'invalid_bitcoin_keys',
    'InvalidBitcoinNetwork': 'invalid_bitcoin_network',
    'InvalidColoringInfo': 'invalid_coloring_info',
    'InvalidConsignment': 'invalid_consignment',
    'InsufficientBitcoins': 'insufficient_funds',
    # from caching
    'UnableToCacheInitialise': 'unable_to_cache_initialise',
    'CacheFetchFailed': 'cache_fetch_failed',
    'FailedToInvalidCache': 'failed_to_invalid_cache',
    'FailedToUpdateCache': 'failed_to_update_cache',
}
