name: Install Python dependencies
description: Install Python dependencies
runs:
  using: "composite"
  steps:
    - name: Install poetry and pyinstaller
      run: |
        pip install poetry
        pip install pyinstaller
      shell: bash

    - name: Install dependencies
      run: poetry install
      shell: bash
